-- =====================================================
-- Strategy Intelligence Layer
-- PLG gap analysis, product suggestions, Stripe linking
-- =====================================================

-- Augment product_definitions with PLG metadata
ALTER TABLE public.product_definitions
  ADD COLUMN IF NOT EXISTS plg_stage       TEXT CHECK (plg_stage IN ('awareness','interest','consideration','conversion','expansion')),
  ADD COLUMN IF NOT EXISTS pillar_id       UUID REFERENCES public.content_pillars(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS stripe_price_id TEXT,
  ADD COLUMN IF NOT EXISTS stripe_product_id TEXT;

CREATE INDEX IF NOT EXISTS product_definitions_pillar_idx   ON public.product_definitions (pillar_id);
CREATE INDEX IF NOT EXISTS product_definitions_plg_idx      ON public.product_definitions (plg_stage);

-- Backfill existing products with best-guess PLG stage
UPDATE public.product_definitions SET plg_stage = 'consideration'
  WHERE product_slug IN ('personal-alignment','business-alignment','brand-alignment','orientation-bundle');

UPDATE public.product_definitions SET plg_stage = 'conversion'
  WHERE product_slug ILIKE '%perception%' OR product_slug ILIKE '%declaration%'
     OR product_slug ILIKE '%alignment-rite%' OR product_slug ILIKE '%rite-%'
     OR product_slug ILIKE '%vcap%';

UPDATE public.product_definitions SET plg_stage = 'expansion'
  WHERE product_slug ILIKE '%rite-iv%' OR product_slug ILIKE '%consulting%'
     OR product_slug ILIKE '%coaching%' OR product_slug ILIKE '%mastermin%';

-- Product suggestions — generated by the strategy engine
CREATE TABLE IF NOT EXISTS public.product_suggestions (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pillar_id        UUID REFERENCES public.content_pillars(id) ON DELETE CASCADE,
  topic_id         UUID REFERENCES public.content_topics(id) ON DELETE SET NULL,
  funnel_stage     TEXT NOT NULL CHECK (funnel_stage IN ('awareness','interest','consideration','conversion','expansion')),
  title            TEXT NOT NULL,
  tagline          TEXT,
  rationale        TEXT,
  format           TEXT, -- 'whitepaper' | 'ebook' | 'mini-course' | 'diagnostic' | 'workshop' | 'gpt-tool'
  corpus_themes    TEXT[] DEFAULT '{}',
  angle_ids        UUID[] DEFAULT '{}',
  status           TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','drafted','accepted','created','dismissed')),
  generated_brief  JSONB DEFAULT '{}',
  linked_product_id UUID,
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS product_suggestions_pillar_idx  ON public.product_suggestions (pillar_id);
CREATE INDEX IF NOT EXISTS product_suggestions_status_idx  ON public.product_suggestions (status);

CREATE TRIGGER update_product_suggestions_updated_at
  BEFORE UPDATE ON public.product_suggestions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

ALTER TABLE public.product_suggestions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "product_suggestions_admin_all" ON public.product_suggestions FOR ALL
  USING (EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role IN ('admin','super_admin')));
